// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivarPuerto(arg1) {
  return window['go']['main']['App']['ActivarPuerto'](arg1);
}

export function ActivarPuertos() {
  return window['go']['main']['App']['ActivarPuertos']();
}

export function DesactivarPuerto(arg1) {
  return window['go']['main']['App']['DesactivarPuerto'](arg1);
}

export function DesactivarPuertos() {
  return window['go']['main']['App']['DesactivarPuertos']();
}

export function EscribirLog() {
  return window['go']['main']['App']['EscribirLog']();
}

export function EscribirLogPc() {
  return window['go']['main']['App']['EscribirLogPc']();
}

export function GetCPU() {
  return window['go']['main']['App']['GetCPU']();
}

export function GetDisk() {
  return window['go']['main']['App']['GetDisk']();
}

export function GetEstadoPuertos() {
  return window['go']['main']['App']['GetEstadoPuertos']();
}

export function GetRam() {
  return window['go']['main']['App']['GetRam']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitBitacora() {
  return window['go']['main']['App']['InitBitacora']();
}

export function Sumar(arg1) {
  return window['go']['main']['App']['Sumar'](arg1);
}
