// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivarPuerto(arg1:string):Promise<string>;

export function ActivarPuertos():Promise<string>;

export function DesactivarPuerto(arg1:string):Promise<string>;

export function DesactivarPuertos():Promise<string>;

export function EscribirLog():Promise<string>;

export function EscribirLogPc():Promise<string>;

export function GetCPU():Promise<string>;

export function GetDisk():Promise<string>;

export function GetEstadoPuertos():Promise<string>;

export function GetRam():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitBitacora():Promise<string>;

export function Sumar(arg1:number):Promise<number>;
